#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassChung
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PM_Chisoyhoc")]
	public partial class CSDL_PMChisoyhocDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchisoyhoc(chisoyhoc instance);
    partial void Updatechisoyhoc(chisoyhoc instance);
    partial void Deletechisoyhoc(chisoyhoc instance);
    partial void Insertchiso_phanloaibien(chiso_phanloaibien instance);
    partial void Updatechiso_phanloaibien(chiso_phanloaibien instance);
    partial void Deletechiso_phanloaibien(chiso_phanloaibien instance);
    partial void Insertchiso_phanloaiDT(chiso_phanloaiDT instance);
    partial void Updatechiso_phanloaiDT(chiso_phanloaiDT instance);
    partial void Deletechiso_phanloaiDT(chiso_phanloaiDT instance);
    partial void Insertr_chiso_bien(r_chiso_bien instance);
    partial void Updater_chiso_bien(r_chiso_bien instance);
    partial void Deleter_chiso_bien(r_chiso_bien instance);
    partial void Insertchiso_DSbien(chiso_DSbien instance);
    partial void Updatechiso_DSbien(chiso_DSbien instance);
    partial void Deletechiso_DSbien(chiso_DSbien instance);
    partial void Insertchiso_DSbienLT(chiso_DSbienLT instance);
    partial void Updatechiso_DSbienLT(chiso_DSbienLT instance);
    partial void Deletechiso_DSbienLT(chiso_DSbienLT instance);
    partial void Insertchiso_DSbienDT(chiso_DSbienDT instance);
    partial void Updatechiso_DSbienDT(chiso_DSbienDT instance);
    partial void Deletechiso_DSbienDT(chiso_DSbienDT instance);
    partial void Insertchiso_GTBienKQ(chiso_GTBienKQ instance);
    partial void Updatechiso_GTBienKQ(chiso_GTBienKQ instance);
    partial void Deletechiso_GTBienKQ(chiso_GTBienKQ instance);
    partial void Insertchiso_DSBienKQ(chiso_DSBienKQ instance);
    partial void Updatechiso_DSBienKQ(chiso_DSBienKQ instance);
    partial void Deletechiso_DSBienKQ(chiso_DSBienKQ instance);
    #endregion
		
		public CSDL_PMChisoyhocDataContext() : 
				base(global::ClassChung.Properties.Settings.Default.PM_ChisoyhocConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public CSDL_PMChisoyhocDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDL_PMChisoyhocDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDL_PMChisoyhocDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSDL_PMChisoyhocDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chisoyhoc> chisoyhocs
		{
			get
			{
				return this.GetTable<chisoyhoc>();
			}
		}
		
		public System.Data.Linq.Table<chiso_phanloaibien> chiso_phanloaibiens
		{
			get
			{
				return this.GetTable<chiso_phanloaibien>();
			}
		}
		
		public System.Data.Linq.Table<chiso_phanloaiDT> chiso_phanloaiDTs
		{
			get
			{
				return this.GetTable<chiso_phanloaiDT>();
			}
		}
		
		public System.Data.Linq.Table<r_chiso_bien> r_chiso_biens
		{
			get
			{
				return this.GetTable<r_chiso_bien>();
			}
		}
		
		public System.Data.Linq.Table<chiso_DSbien> chiso_DSbiens
		{
			get
			{
				return this.GetTable<chiso_DSbien>();
			}
		}
		
		public System.Data.Linq.Table<chiso_DSbienLT> chiso_DSbienLTs
		{
			get
			{
				return this.GetTable<chiso_DSbienLT>();
			}
		}
		
		public System.Data.Linq.Table<chiso_DSbienDT> chiso_DSbienDTs
		{
			get
			{
				return this.GetTable<chiso_DSbienDT>();
			}
		}
		
		public System.Data.Linq.Table<chiso_GTBienKQ> chiso_GTBienKQs
		{
			get
			{
				return this.GetTable<chiso_GTBienKQ>();
			}
		}
		
		public System.Data.Linq.Table<chiso_DSBienKQ> chiso_DSBienKQs
		{
			get
			{
				return this.GetTable<chiso_DSBienKQ>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chisoyhoc")]
	public partial class chisoyhoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _machiso;
		
		private string _tenchiso;
		
		private string _phanloai;
		
		private string _mucdich;
		
		private string _ungdung;
		
		private string _phuongphap;
		
		private string _diengiaiketqua;
		
		private string _ghichu;
		
		private string _tltk;
		
		private System.Nullable<double> _thongdung;
		
		private EntitySet<r_chiso_bien> _r_chiso_biens;
		
		private EntitySet<chiso_DSBienKQ> _chiso_DSBienKQs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmachisoChanging(string value);
    partial void OnmachisoChanged();
    partial void OntenchisoChanging(string value);
    partial void OntenchisoChanged();
    partial void OnphanloaiChanging(string value);
    partial void OnphanloaiChanged();
    partial void OnmucdichChanging(string value);
    partial void OnmucdichChanged();
    partial void OnungdungChanging(string value);
    partial void OnungdungChanged();
    partial void OnphuongphapChanging(string value);
    partial void OnphuongphapChanged();
    partial void OndiengiaiketquaChanging(string value);
    partial void OndiengiaiketquaChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OntltkChanging(string value);
    partial void OntltkChanged();
    partial void OnthongdungChanging(System.Nullable<double> value);
    partial void OnthongdungChanged();
    #endregion
		
		public chisoyhoc()
		{
			this._r_chiso_biens = new EntitySet<r_chiso_bien>(new Action<r_chiso_bien>(this.attach_r_chiso_biens), new Action<r_chiso_bien>(this.detach_r_chiso_biens));
			this._chiso_DSBienKQs = new EntitySet<chiso_DSBienKQ>(new Action<chiso_DSBienKQ>(this.attach_chiso_DSBienKQs), new Action<chiso_DSBienKQ>(this.detach_chiso_DSBienKQs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machiso", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machiso
		{
			get
			{
				return this._machiso;
			}
			set
			{
				if ((this._machiso != value))
				{
					this.OnmachisoChanging(value);
					this.SendPropertyChanging();
					this._machiso = value;
					this.SendPropertyChanged("machiso");
					this.OnmachisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenchiso", DbType="NVarChar(255)")]
		public string tenchiso
		{
			get
			{
				return this._tenchiso;
			}
			set
			{
				if ((this._tenchiso != value))
				{
					this.OntenchisoChanging(value);
					this.SendPropertyChanging();
					this._tenchiso = value;
					this.SendPropertyChanged("tenchiso");
					this.OntenchisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanloai", DbType="NVarChar(255)")]
		public string phanloai
		{
			get
			{
				return this._phanloai;
			}
			set
			{
				if ((this._phanloai != value))
				{
					this.OnphanloaiChanging(value);
					this.SendPropertyChanging();
					this._phanloai = value;
					this.SendPropertyChanged("phanloai");
					this.OnphanloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucdich", DbType="NVarChar(255)")]
		public string mucdich
		{
			get
			{
				return this._mucdich;
			}
			set
			{
				if ((this._mucdich != value))
				{
					this.OnmucdichChanging(value);
					this.SendPropertyChanging();
					this._mucdich = value;
					this.SendPropertyChanged("mucdich");
					this.OnmucdichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ungdung", DbType="NVarChar(255)")]
		public string ungdung
		{
			get
			{
				return this._ungdung;
			}
			set
			{
				if ((this._ungdung != value))
				{
					this.OnungdungChanging(value);
					this.SendPropertyChanging();
					this._ungdung = value;
					this.SendPropertyChanged("ungdung");
					this.OnungdungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuongphap", DbType="NVarChar(MAX)")]
		public string phuongphap
		{
			get
			{
				return this._phuongphap;
			}
			set
			{
				if ((this._phuongphap != value))
				{
					this.OnphuongphapChanging(value);
					this.SendPropertyChanging();
					this._phuongphap = value;
					this.SendPropertyChanged("phuongphap");
					this.OnphuongphapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diengiaiketqua", DbType="NVarChar(MAX)")]
		public string diengiaiketqua
		{
			get
			{
				return this._diengiaiketqua;
			}
			set
			{
				if ((this._diengiaiketqua != value))
				{
					this.OndiengiaiketquaChanging(value);
					this.SendPropertyChanging();
					this._diengiaiketqua = value;
					this.SendPropertyChanged("diengiaiketqua");
					this.OndiengiaiketquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(MAX)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tltk", DbType="NVarChar(MAX)")]
		public string tltk
		{
			get
			{
				return this._tltk;
			}
			set
			{
				if ((this._tltk != value))
				{
					this.OntltkChanging(value);
					this.SendPropertyChanging();
					this._tltk = value;
					this.SendPropertyChanged("tltk");
					this.OntltkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thongdung", DbType="Float")]
		public System.Nullable<double> thongdung
		{
			get
			{
				return this._thongdung;
			}
			set
			{
				if ((this._thongdung != value))
				{
					this.OnthongdungChanging(value);
					this.SendPropertyChanging();
					this._thongdung = value;
					this.SendPropertyChanged("thongdung");
					this.OnthongdungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chisoyhoc_r_chiso_bien", Storage="_r_chiso_biens", ThisKey="machiso", OtherKey="machiso")]
		public EntitySet<r_chiso_bien> r_chiso_biens
		{
			get
			{
				return this._r_chiso_biens;
			}
			set
			{
				this._r_chiso_biens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chisoyhoc_chiso_DSBienKQ", Storage="_chiso_DSBienKQs", ThisKey="machiso", OtherKey="machiso")]
		public EntitySet<chiso_DSBienKQ> chiso_DSBienKQs
		{
			get
			{
				return this._chiso_DSBienKQs;
			}
			set
			{
				this._chiso_DSBienKQs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_chiso_biens(r_chiso_bien entity)
		{
			this.SendPropertyChanging();
			entity.chisoyhoc = this;
		}
		
		private void detach_r_chiso_biens(r_chiso_bien entity)
		{
			this.SendPropertyChanging();
			entity.chisoyhoc = null;
		}
		
		private void attach_chiso_DSBienKQs(chiso_DSBienKQ entity)
		{
			this.SendPropertyChanging();
			entity.chisoyhoc = this;
		}
		
		private void detach_chiso_DSBienKQs(chiso_DSBienKQ entity)
		{
			this.SendPropertyChanging();
			entity.chisoyhoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_phanloaibien")]
	public partial class chiso_phanloaibien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPhanloaibien;
		
		private string _phanloai;
		
		private EntitySet<chiso_DSbien> _chiso_DSbiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhanloaibienChanging(int value);
    partial void OnIDPhanloaibienChanged();
    partial void OnphanloaiChanging(string value);
    partial void OnphanloaiChanged();
    #endregion
		
		public chiso_phanloaibien()
		{
			this._chiso_DSbiens = new EntitySet<chiso_DSbien>(new Action<chiso_DSbien>(this.attach_chiso_DSbiens), new Action<chiso_DSbien>(this.detach_chiso_DSbiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhanloaibien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDPhanloaibien
		{
			get
			{
				return this._IDPhanloaibien;
			}
			set
			{
				if ((this._IDPhanloaibien != value))
				{
					this.OnIDPhanloaibienChanging(value);
					this.SendPropertyChanging();
					this._IDPhanloaibien = value;
					this.SendPropertyChanged("IDPhanloaibien");
					this.OnIDPhanloaibienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phanloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phanloai
		{
			get
			{
				return this._phanloai;
			}
			set
			{
				if ((this._phanloai != value))
				{
					this.OnphanloaiChanging(value);
					this.SendPropertyChanging();
					this._phanloai = value;
					this.SendPropertyChanged("phanloai");
					this.OnphanloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_phanloaibien_chiso_DSbien", Storage="_chiso_DSbiens", ThisKey="IDPhanloaibien", OtherKey="IDPhanloaibien")]
		public EntitySet<chiso_DSbien> chiso_DSbiens
		{
			get
			{
				return this._chiso_DSbiens;
			}
			set
			{
				this._chiso_DSbiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiso_DSbiens(chiso_DSbien entity)
		{
			this.SendPropertyChanging();
			entity.chiso_phanloaibien = this;
		}
		
		private void detach_chiso_DSbiens(chiso_DSbien entity)
		{
			this.SendPropertyChanging();
			entity.chiso_phanloaibien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_phanloaiDT")]
	public partial class chiso_phanloaiDT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDphanloaiDT;
		
		private string _ten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDphanloaiDTChanging(int value);
    partial void OnIDphanloaiDTChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    #endregion
		
		public chiso_phanloaiDT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDphanloaiDT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDphanloaiDT
		{
			get
			{
				return this._IDphanloaiDT;
			}
			set
			{
				if ((this._IDphanloaiDT != value))
				{
					this.OnIDphanloaiDTChanging(value);
					this.SendPropertyChanging();
					this._IDphanloaiDT = value;
					this.SendPropertyChanged("IDphanloaiDT");
					this.OnIDphanloaiDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.r_chiso_bien")]
	public partial class r_chiso_bien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Chiso_Bien;
		
		private string _machiso;
		
		private int _IDBien;
		
		private EntityRef<chisoyhoc> _chisoyhoc;
		
		private EntityRef<chiso_DSbien> _chiso_DSbien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Chiso_BienChanging(int value);
    partial void OnID_Chiso_BienChanged();
    partial void OnmachisoChanging(string value);
    partial void OnmachisoChanged();
    partial void OnIDBienChanging(int value);
    partial void OnIDBienChanged();
    #endregion
		
		public r_chiso_bien()
		{
			this._chisoyhoc = default(EntityRef<chisoyhoc>);
			this._chiso_DSbien = default(EntityRef<chiso_DSbien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Chiso_Bien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Chiso_Bien
		{
			get
			{
				return this._ID_Chiso_Bien;
			}
			set
			{
				if ((this._ID_Chiso_Bien != value))
				{
					this.OnID_Chiso_BienChanging(value);
					this.SendPropertyChanging();
					this._ID_Chiso_Bien = value;
					this.SendPropertyChanged("ID_Chiso_Bien");
					this.OnID_Chiso_BienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machiso", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string machiso
		{
			get
			{
				return this._machiso;
			}
			set
			{
				if ((this._machiso != value))
				{
					if (this._chisoyhoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmachisoChanging(value);
					this.SendPropertyChanging();
					this._machiso = value;
					this.SendPropertyChanged("machiso");
					this.OnmachisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBien", DbType="Int NOT NULL")]
		public int IDBien
		{
			get
			{
				return this._IDBien;
			}
			set
			{
				if ((this._IDBien != value))
				{
					if (this._chiso_DSbien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBienChanging(value);
					this.SendPropertyChanging();
					this._IDBien = value;
					this.SendPropertyChanged("IDBien");
					this.OnIDBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chisoyhoc_r_chiso_bien", Storage="_chisoyhoc", ThisKey="machiso", OtherKey="machiso", IsForeignKey=true)]
		public chisoyhoc chisoyhoc
		{
			get
			{
				return this._chisoyhoc.Entity;
			}
			set
			{
				chisoyhoc previousValue = this._chisoyhoc.Entity;
				if (((previousValue != value) 
							|| (this._chisoyhoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chisoyhoc.Entity = null;
						previousValue.r_chiso_biens.Remove(this);
					}
					this._chisoyhoc.Entity = value;
					if ((value != null))
					{
						value.r_chiso_biens.Add(this);
						this._machiso = value.machiso;
					}
					else
					{
						this._machiso = default(string);
					}
					this.SendPropertyChanged("chisoyhoc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_r_chiso_bien", Storage="_chiso_DSbien", ThisKey="IDBien", OtherKey="IDbien", IsForeignKey=true)]
		public chiso_DSbien chiso_DSbien
		{
			get
			{
				return this._chiso_DSbien.Entity;
			}
			set
			{
				chiso_DSbien previousValue = this._chiso_DSbien.Entity;
				if (((previousValue != value) 
							|| (this._chiso_DSbien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chiso_DSbien.Entity = null;
						previousValue.r_chiso_biens.Remove(this);
					}
					this._chiso_DSbien.Entity = value;
					if ((value != null))
					{
						value.r_chiso_biens.Add(this);
						this._IDBien = value.IDbien;
					}
					else
					{
						this._IDBien = default(int);
					}
					this.SendPropertyChanged("chiso_DSbien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_DSbien")]
	public partial class chiso_DSbien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDbien;
		
		private string _tenbien;
		
		private string _tendaydu;
		
		private int _IDPhanloaibien;
		
		private bool _biengoc;
		
		private string _mota;
		
		private string _ghichu;
		
		private System.Nullable<bool> _NB;
		
		private System.Nullable<bool> _XN;
		
		private System.Nullable<bool> _CT;
		
		private System.Nullable<bool> _TD;
		
		private int _IDbiengoc;
		
		private EntitySet<r_chiso_bien> _r_chiso_biens;
		
		private EntitySet<chiso_DSbienLT> _chiso_DSbienLTs;
		
		private EntitySet<chiso_DSbienDT> _chiso_DSbienDTs;
		
		private EntityRef<chiso_phanloaibien> _chiso_phanloaibien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDbienChanging(int value);
    partial void OnIDbienChanged();
    partial void OntenbienChanging(string value);
    partial void OntenbienChanged();
    partial void OntendayduChanging(string value);
    partial void OntendayduChanged();
    partial void OnIDPhanloaibienChanging(int value);
    partial void OnIDPhanloaibienChanged();
    partial void OnbiengocChanging(bool value);
    partial void OnbiengocChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OnNBChanging(System.Nullable<bool> value);
    partial void OnNBChanged();
    partial void OnXNChanging(System.Nullable<bool> value);
    partial void OnXNChanged();
    partial void OnCTChanging(System.Nullable<bool> value);
    partial void OnCTChanged();
    partial void OnTDChanging(System.Nullable<bool> value);
    partial void OnTDChanged();
    partial void OnIDbiengocChanging(int value);
    partial void OnIDbiengocChanged();
    #endregion
		
		public chiso_DSbien()
		{
			this._r_chiso_biens = new EntitySet<r_chiso_bien>(new Action<r_chiso_bien>(this.attach_r_chiso_biens), new Action<r_chiso_bien>(this.detach_r_chiso_biens));
			this._chiso_DSbienLTs = new EntitySet<chiso_DSbienLT>(new Action<chiso_DSbienLT>(this.attach_chiso_DSbienLTs), new Action<chiso_DSbienLT>(this.detach_chiso_DSbienLTs));
			this._chiso_DSbienDTs = new EntitySet<chiso_DSbienDT>(new Action<chiso_DSbienDT>(this.attach_chiso_DSbienDTs), new Action<chiso_DSbienDT>(this.detach_chiso_DSbienDTs));
			this._chiso_phanloaibien = default(EntityRef<chiso_phanloaibien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDbien
		{
			get
			{
				return this._IDbien;
			}
			set
			{
				if ((this._IDbien != value))
				{
					this.OnIDbienChanging(value);
					this.SendPropertyChanging();
					this._IDbien = value;
					this.SendPropertyChanged("IDbien");
					this.OnIDbienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenbien", DbType="NChar(500) NOT NULL", CanBeNull=false)]
		public string tenbien
		{
			get
			{
				return this._tenbien;
			}
			set
			{
				if ((this._tenbien != value))
				{
					this.OntenbienChanging(value);
					this.SendPropertyChanging();
					this._tenbien = value;
					this.SendPropertyChanged("tenbien");
					this.OntenbienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendaydu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string tendaydu
		{
			get
			{
				return this._tendaydu;
			}
			set
			{
				if ((this._tendaydu != value))
				{
					this.OntendayduChanging(value);
					this.SendPropertyChanging();
					this._tendaydu = value;
					this.SendPropertyChanged("tendaydu");
					this.OntendayduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhanloaibien", DbType="Int NOT NULL")]
		public int IDPhanloaibien
		{
			get
			{
				return this._IDPhanloaibien;
			}
			set
			{
				if ((this._IDPhanloaibien != value))
				{
					if (this._chiso_phanloaibien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhanloaibienChanging(value);
					this.SendPropertyChanging();
					this._IDPhanloaibien = value;
					this.SendPropertyChanged("IDPhanloaibien");
					this.OnIDPhanloaibienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_biengoc", DbType="Bit NOT NULL")]
		public bool biengoc
		{
			get
			{
				return this._biengoc;
			}
			set
			{
				if ((this._biengoc != value))
				{
					this.OnbiengocChanging(value);
					this.SendPropertyChanging();
					this._biengoc = value;
					this.SendPropertyChanged("biengoc");
					this.OnbiengocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(200)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(200)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NB", DbType="Bit")]
		public System.Nullable<bool> NB
		{
			get
			{
				return this._NB;
			}
			set
			{
				if ((this._NB != value))
				{
					this.OnNBChanging(value);
					this.SendPropertyChanging();
					this._NB = value;
					this.SendPropertyChanged("NB");
					this.OnNBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XN", DbType="Bit")]
		public System.Nullable<bool> XN
		{
			get
			{
				return this._XN;
			}
			set
			{
				if ((this._XN != value))
				{
					this.OnXNChanging(value);
					this.SendPropertyChanging();
					this._XN = value;
					this.SendPropertyChanged("XN");
					this.OnXNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT", DbType="Bit")]
		public System.Nullable<bool> CT
		{
			get
			{
				return this._CT;
			}
			set
			{
				if ((this._CT != value))
				{
					this.OnCTChanging(value);
					this.SendPropertyChanging();
					this._CT = value;
					this.SendPropertyChanged("CT");
					this.OnCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TD", DbType="Bit")]
		public System.Nullable<bool> TD
		{
			get
			{
				return this._TD;
			}
			set
			{
				if ((this._TD != value))
				{
					this.OnTDChanging(value);
					this.SendPropertyChanging();
					this._TD = value;
					this.SendPropertyChanged("TD");
					this.OnTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbiengoc", DbType="Int NOT NULL")]
		public int IDbiengoc
		{
			get
			{
				return this._IDbiengoc;
			}
			set
			{
				if ((this._IDbiengoc != value))
				{
					this.OnIDbiengocChanging(value);
					this.SendPropertyChanging();
					this._IDbiengoc = value;
					this.SendPropertyChanged("IDbiengoc");
					this.OnIDbiengocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_r_chiso_bien", Storage="_r_chiso_biens", ThisKey="IDbien", OtherKey="IDBien")]
		public EntitySet<r_chiso_bien> r_chiso_biens
		{
			get
			{
				return this._r_chiso_biens;
			}
			set
			{
				this._r_chiso_biens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_chiso_DSbienLT", Storage="_chiso_DSbienLTs", ThisKey="IDbien", OtherKey="ID_Bien")]
		public EntitySet<chiso_DSbienLT> chiso_DSbienLTs
		{
			get
			{
				return this._chiso_DSbienLTs;
			}
			set
			{
				this._chiso_DSbienLTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_chiso_DSbienDT", Storage="_chiso_DSbienDTs", ThisKey="IDbien", OtherKey="IDBien")]
		public EntitySet<chiso_DSbienDT> chiso_DSbienDTs
		{
			get
			{
				return this._chiso_DSbienDTs;
			}
			set
			{
				this._chiso_DSbienDTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_phanloaibien_chiso_DSbien", Storage="_chiso_phanloaibien", ThisKey="IDPhanloaibien", OtherKey="IDPhanloaibien", IsForeignKey=true)]
		public chiso_phanloaibien chiso_phanloaibien
		{
			get
			{
				return this._chiso_phanloaibien.Entity;
			}
			set
			{
				chiso_phanloaibien previousValue = this._chiso_phanloaibien.Entity;
				if (((previousValue != value) 
							|| (this._chiso_phanloaibien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chiso_phanloaibien.Entity = null;
						previousValue.chiso_DSbiens.Remove(this);
					}
					this._chiso_phanloaibien.Entity = value;
					if ((value != null))
					{
						value.chiso_DSbiens.Add(this);
						this._IDPhanloaibien = value.IDPhanloaibien;
					}
					else
					{
						this._IDPhanloaibien = default(int);
					}
					this.SendPropertyChanged("chiso_phanloaibien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_r_chiso_biens(r_chiso_bien entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = this;
		}
		
		private void detach_r_chiso_biens(r_chiso_bien entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = null;
		}
		
		private void attach_chiso_DSbienLTs(chiso_DSbienLT entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = this;
		}
		
		private void detach_chiso_DSbienLTs(chiso_DSbienLT entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = null;
		}
		
		private void attach_chiso_DSbienDTs(chiso_DSbienDT entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = this;
		}
		
		private void detach_chiso_DSbienDTs(chiso_DSbienDT entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSbien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_DSbienLT")]
	public partial class chiso_DSbienLT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBienLT;
		
		private int _ID_Bien;
		
		private string _donvichuan;
		
		private int _IDphanloaidonvi;
		
		private string _tenkhac;
		
		private EntityRef<chiso_DSbien> _chiso_DSbien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBienLTChanging(int value);
    partial void OnIDBienLTChanged();
    partial void OnID_BienChanging(int value);
    partial void OnID_BienChanged();
    partial void OndonvichuanChanging(string value);
    partial void OndonvichuanChanged();
    partial void OnIDphanloaidonviChanging(int value);
    partial void OnIDphanloaidonviChanged();
    partial void OntenkhacChanging(string value);
    partial void OntenkhacChanged();
    #endregion
		
		public chiso_DSbienLT()
		{
			this._chiso_DSbien = default(EntityRef<chiso_DSbien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBienLT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBienLT
		{
			get
			{
				return this._IDBienLT;
			}
			set
			{
				if ((this._IDBienLT != value))
				{
					this.OnIDBienLTChanging(value);
					this.SendPropertyChanging();
					this._IDBienLT = value;
					this.SendPropertyChanged("IDBienLT");
					this.OnIDBienLTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Bien", DbType="Int NOT NULL")]
		public int ID_Bien
		{
			get
			{
				return this._ID_Bien;
			}
			set
			{
				if ((this._ID_Bien != value))
				{
					if (this._chiso_DSbien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_BienChanging(value);
					this.SendPropertyChanging();
					this._ID_Bien = value;
					this.SendPropertyChanged("ID_Bien");
					this.OnID_BienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvichuan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string donvichuan
		{
			get
			{
				return this._donvichuan;
			}
			set
			{
				if ((this._donvichuan != value))
				{
					this.OndonvichuanChanging(value);
					this.SendPropertyChanging();
					this._donvichuan = value;
					this.SendPropertyChanged("donvichuan");
					this.OndonvichuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDphanloaidonvi", DbType="Int NOT NULL")]
		public int IDphanloaidonvi
		{
			get
			{
				return this._IDphanloaidonvi;
			}
			set
			{
				if ((this._IDphanloaidonvi != value))
				{
					this.OnIDphanloaidonviChanging(value);
					this.SendPropertyChanging();
					this._IDphanloaidonvi = value;
					this.SendPropertyChanged("IDphanloaidonvi");
					this.OnIDphanloaidonviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhac", DbType="NVarChar(255)")]
		public string tenkhac
		{
			get
			{
				return this._tenkhac;
			}
			set
			{
				if ((this._tenkhac != value))
				{
					this.OntenkhacChanging(value);
					this.SendPropertyChanging();
					this._tenkhac = value;
					this.SendPropertyChanged("tenkhac");
					this.OntenkhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_chiso_DSbienLT", Storage="_chiso_DSbien", ThisKey="ID_Bien", OtherKey="IDbien", IsForeignKey=true)]
		public chiso_DSbien chiso_DSbien
		{
			get
			{
				return this._chiso_DSbien.Entity;
			}
			set
			{
				chiso_DSbien previousValue = this._chiso_DSbien.Entity;
				if (((previousValue != value) 
							|| (this._chiso_DSbien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chiso_DSbien.Entity = null;
						previousValue.chiso_DSbienLTs.Remove(this);
					}
					this._chiso_DSbien.Entity = value;
					if ((value != null))
					{
						value.chiso_DSbienLTs.Add(this);
						this._ID_Bien = value.IDbien;
					}
					else
					{
						this._ID_Bien = default(int);
					}
					this.SendPropertyChanged("chiso_DSbien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_DSbienDT")]
	public partial class chiso_DSbienDT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBienDT;
		
		private int _IDBien;
		
		private int _thutu;
		
		private string _giatri;
		
		private double _diem;
		
		private string _limit;
		
		private bool _xuly;
		
		private EntityRef<chiso_DSbien> _chiso_DSbien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBienDTChanging(int value);
    partial void OnIDBienDTChanged();
    partial void OnIDBienChanging(int value);
    partial void OnIDBienChanged();
    partial void OnthutuChanging(int value);
    partial void OnthutuChanged();
    partial void OngiatriChanging(string value);
    partial void OngiatriChanged();
    partial void OndiemChanging(double value);
    partial void OndiemChanged();
    partial void OnlimitChanging(string value);
    partial void OnlimitChanged();
    partial void OnxulyChanging(bool value);
    partial void OnxulyChanged();
    #endregion
		
		public chiso_DSbienDT()
		{
			this._chiso_DSbien = default(EntityRef<chiso_DSbien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBienDT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBienDT
		{
			get
			{
				return this._IDBienDT;
			}
			set
			{
				if ((this._IDBienDT != value))
				{
					this.OnIDBienDTChanging(value);
					this.SendPropertyChanging();
					this._IDBienDT = value;
					this.SendPropertyChanged("IDBienDT");
					this.OnIDBienDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBien", DbType="Int NOT NULL")]
		public int IDBien
		{
			get
			{
				return this._IDBien;
			}
			set
			{
				if ((this._IDBien != value))
				{
					if (this._chiso_DSbien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBienChanging(value);
					this.SendPropertyChanging();
					this._IDBien = value;
					this.SendPropertyChanged("IDBien");
					this.OnIDBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thutu", DbType="Int NOT NULL")]
		public int thutu
		{
			get
			{
				return this._thutu;
			}
			set
			{
				if ((this._thutu != value))
				{
					this.OnthutuChanging(value);
					this.SendPropertyChanging();
					this._thutu = value;
					this.SendPropertyChanged("thutu");
					this.OnthutuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatri", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string giatri
		{
			get
			{
				return this._giatri;
			}
			set
			{
				if ((this._giatri != value))
				{
					this.OngiatriChanging(value);
					this.SendPropertyChanging();
					this._giatri = value;
					this.SendPropertyChanged("giatri");
					this.OngiatriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diem", DbType="Float NOT NULL")]
		public double diem
		{
			get
			{
				return this._diem;
			}
			set
			{
				if ((this._diem != value))
				{
					this.OndiemChanging(value);
					this.SendPropertyChanging();
					this._diem = value;
					this.SendPropertyChanged("diem");
					this.OndiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limit", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string limit
		{
			get
			{
				return this._limit;
			}
			set
			{
				if ((this._limit != value))
				{
					this.OnlimitChanging(value);
					this.SendPropertyChanging();
					this._limit = value;
					this.SendPropertyChanged("limit");
					this.OnlimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuly", DbType="Bit NOT NULL")]
		public bool xuly
		{
			get
			{
				return this._xuly;
			}
			set
			{
				if ((this._xuly != value))
				{
					this.OnxulyChanging(value);
					this.SendPropertyChanging();
					this._xuly = value;
					this.SendPropertyChanged("xuly");
					this.OnxulyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSbien_chiso_DSbienDT", Storage="_chiso_DSbien", ThisKey="IDBien", OtherKey="IDbien", IsForeignKey=true)]
		public chiso_DSbien chiso_DSbien
		{
			get
			{
				return this._chiso_DSbien.Entity;
			}
			set
			{
				chiso_DSbien previousValue = this._chiso_DSbien.Entity;
				if (((previousValue != value) 
							|| (this._chiso_DSbien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chiso_DSbien.Entity = null;
						previousValue.chiso_DSbienDTs.Remove(this);
					}
					this._chiso_DSbien.Entity = value;
					if ((value != null))
					{
						value.chiso_DSbienDTs.Add(this);
						this._IDBien = value.IDbien;
					}
					else
					{
						this._IDBien = default(int);
					}
					this.SendPropertyChanged("chiso_DSbien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_GTBienKQ")]
	public partial class chiso_GTBienKQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDGTBienKQ;
		
		private int _IDBienKQ;
		
		private double _DiemLL;
		
		private double _DiemUL;
		
		private string _Diengiai;
		
		private EntityRef<chiso_DSBienKQ> _chiso_DSBienKQ;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDGTBienKQChanging(int value);
    partial void OnIDGTBienKQChanged();
    partial void OnIDBienKQChanging(int value);
    partial void OnIDBienKQChanged();
    partial void OnDiemLLChanging(double value);
    partial void OnDiemLLChanged();
    partial void OnDiemULChanging(double value);
    partial void OnDiemULChanged();
    partial void OnDiengiaiChanging(string value);
    partial void OnDiengiaiChanged();
    #endregion
		
		public chiso_GTBienKQ()
		{
			this._chiso_DSBienKQ = default(EntityRef<chiso_DSBienKQ>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGTBienKQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDGTBienKQ
		{
			get
			{
				return this._IDGTBienKQ;
			}
			set
			{
				if ((this._IDGTBienKQ != value))
				{
					this.OnIDGTBienKQChanging(value);
					this.SendPropertyChanging();
					this._IDGTBienKQ = value;
					this.SendPropertyChanged("IDGTBienKQ");
					this.OnIDGTBienKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBienKQ", DbType="Int NOT NULL")]
		public int IDBienKQ
		{
			get
			{
				return this._IDBienKQ;
			}
			set
			{
				if ((this._IDBienKQ != value))
				{
					if (this._chiso_DSBienKQ.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDBienKQChanging(value);
					this.SendPropertyChanging();
					this._IDBienKQ = value;
					this.SendPropertyChanged("IDBienKQ");
					this.OnIDBienKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemLL", DbType="Float NOT NULL")]
		public double DiemLL
		{
			get
			{
				return this._DiemLL;
			}
			set
			{
				if ((this._DiemLL != value))
				{
					this.OnDiemLLChanging(value);
					this.SendPropertyChanging();
					this._DiemLL = value;
					this.SendPropertyChanged("DiemLL");
					this.OnDiemLLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemUL", DbType="Float NOT NULL")]
		public double DiemUL
		{
			get
			{
				return this._DiemUL;
			}
			set
			{
				if ((this._DiemUL != value))
				{
					this.OnDiemULChanging(value);
					this.SendPropertyChanging();
					this._DiemUL = value;
					this.SendPropertyChanged("DiemUL");
					this.OnDiemULChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diengiai", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Diengiai
		{
			get
			{
				return this._Diengiai;
			}
			set
			{
				if ((this._Diengiai != value))
				{
					this.OnDiengiaiChanging(value);
					this.SendPropertyChanging();
					this._Diengiai = value;
					this.SendPropertyChanged("Diengiai");
					this.OnDiengiaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSBienKQ_chiso_GTBienKQ", Storage="_chiso_DSBienKQ", ThisKey="IDBienKQ", OtherKey="IDBienKQ", IsForeignKey=true)]
		public chiso_DSBienKQ chiso_DSBienKQ
		{
			get
			{
				return this._chiso_DSBienKQ.Entity;
			}
			set
			{
				chiso_DSBienKQ previousValue = this._chiso_DSBienKQ.Entity;
				if (((previousValue != value) 
							|| (this._chiso_DSBienKQ.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chiso_DSBienKQ.Entity = null;
						previousValue.chiso_GTBienKQs.Remove(this);
					}
					this._chiso_DSBienKQ.Entity = value;
					if ((value != null))
					{
						value.chiso_GTBienKQs.Add(this);
						this._IDBienKQ = value.IDBienKQ;
					}
					else
					{
						this._IDBienKQ = default(int);
					}
					this.SendPropertyChanged("chiso_DSBienKQ");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chiso_DSBienKQ")]
	public partial class chiso_DSBienKQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBienKQ;
		
		private string _TenbienKQ;
		
		private string _TendayduKQ;
		
		private string _machiso;
		
		private EntitySet<chiso_GTBienKQ> _chiso_GTBienKQs;
		
		private EntityRef<chisoyhoc> _chisoyhoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBienKQChanging(int value);
    partial void OnIDBienKQChanged();
    partial void OnTenbienKQChanging(string value);
    partial void OnTenbienKQChanged();
    partial void OnTendayduKQChanging(string value);
    partial void OnTendayduKQChanged();
    partial void OnmachisoChanging(string value);
    partial void OnmachisoChanged();
    #endregion
		
		public chiso_DSBienKQ()
		{
			this._chiso_GTBienKQs = new EntitySet<chiso_GTBienKQ>(new Action<chiso_GTBienKQ>(this.attach_chiso_GTBienKQs), new Action<chiso_GTBienKQ>(this.detach_chiso_GTBienKQs));
			this._chisoyhoc = default(EntityRef<chisoyhoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBienKQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDBienKQ
		{
			get
			{
				return this._IDBienKQ;
			}
			set
			{
				if ((this._IDBienKQ != value))
				{
					this.OnIDBienKQChanging(value);
					this.SendPropertyChanging();
					this._IDBienKQ = value;
					this.SendPropertyChanged("IDBienKQ");
					this.OnIDBienKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenbienKQ", DbType="NVarChar(255)")]
		public string TenbienKQ
		{
			get
			{
				return this._TenbienKQ;
			}
			set
			{
				if ((this._TenbienKQ != value))
				{
					this.OnTenbienKQChanging(value);
					this.SendPropertyChanging();
					this._TenbienKQ = value;
					this.SendPropertyChanged("TenbienKQ");
					this.OnTenbienKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TendayduKQ", DbType="NVarChar(255)")]
		public string TendayduKQ
		{
			get
			{
				return this._TendayduKQ;
			}
			set
			{
				if ((this._TendayduKQ != value))
				{
					this.OnTendayduKQChanging(value);
					this.SendPropertyChanging();
					this._TendayduKQ = value;
					this.SendPropertyChanged("TendayduKQ");
					this.OnTendayduKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machiso", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string machiso
		{
			get
			{
				return this._machiso;
			}
			set
			{
				if ((this._machiso != value))
				{
					if (this._chisoyhoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmachisoChanging(value);
					this.SendPropertyChanging();
					this._machiso = value;
					this.SendPropertyChanged("machiso");
					this.OnmachisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chiso_DSBienKQ_chiso_GTBienKQ", Storage="_chiso_GTBienKQs", ThisKey="IDBienKQ", OtherKey="IDBienKQ")]
		public EntitySet<chiso_GTBienKQ> chiso_GTBienKQs
		{
			get
			{
				return this._chiso_GTBienKQs;
			}
			set
			{
				this._chiso_GTBienKQs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chisoyhoc_chiso_DSBienKQ", Storage="_chisoyhoc", ThisKey="machiso", OtherKey="machiso", IsForeignKey=true)]
		public chisoyhoc chisoyhoc
		{
			get
			{
				return this._chisoyhoc.Entity;
			}
			set
			{
				chisoyhoc previousValue = this._chisoyhoc.Entity;
				if (((previousValue != value) 
							|| (this._chisoyhoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chisoyhoc.Entity = null;
						previousValue.chiso_DSBienKQs.Remove(this);
					}
					this._chisoyhoc.Entity = value;
					if ((value != null))
					{
						value.chiso_DSBienKQs.Add(this);
						this._machiso = value.machiso;
					}
					else
					{
						this._machiso = default(string);
					}
					this.SendPropertyChanged("chisoyhoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chiso_GTBienKQs(chiso_GTBienKQ entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSBienKQ = this;
		}
		
		private void detach_chiso_GTBienKQs(chiso_GTBienKQ entity)
		{
			this.SendPropertyChanging();
			entity.chiso_DSBienKQ = null;
		}
	}
}
#pragma warning restore 1591
