//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassChung.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2I7PF6U;Initial Catalog=PM_Chisoyhoc;User ID=sa;Password=Anhy" +
            "eu1em")]
        public string PM_ChisoyhocConnectionString1 {
            get {
                return ((string)(this["PM_ChisoyhocConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SP0BRKD;Initial Catalog=PM_Chisoyhoc;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=123")]
        public string PM_ChisoyhocConnectionString2 {
            get {
                return ((string)(this["PM_ChisoyhocConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=103.140.249.152;Initial Catalog=PM_Chisoyhoc;Persist Security Info=Tr" +
            "ue;User ID=chisoyhoc;Password=Ahihi123")]
        public string PM_ChisoyhocConnectionString3 {
            get {
                return ((string)(this["PM_ChisoyhocConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SP0BRKD;Initial Catalog=PM_Chisoyhoc;Persist Security Info=Tr" +
            "ue;User ID=sa;Password=123")]
        public string PM_ChisoyhocConnectionString {
            get {
                return ((string)(this["PM_ChisoyhocConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SP0BRKD;Initial Catalog=PM_Chisoyhoc;Integrated Security=True" +
            "")]
        public string PM_ChisoyhocConnectionString4 {
            get {
                return ((string)(this["PM_ChisoyhocConnectionString4"]));
            }
        }
    }
}
